config/routes.rb
Rails.application.routes.draw do

  root to: 'shots#index'

  resources :shots do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show]

  # devise_for :users

  devise_scope :user do
    # registrations
    get 'cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get 'register', to: 'users/registrations#new', as: :new_user_registration
    get 'edit', to: 'users/registrations#edit', as: :edit_user_registration
    patch '', to: 'users/registrations#update', as: :user_registration
    put '', to: 'users/registrations#update'
    delete '', to: 'users/registrations#destroy'
    post '', to: 'users/registrations#create'

    # session
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session

    # password
    get 'password/new', to: 'devise/passwords#new', as: :new_user_password
    get 'password/edit', to: 'devise/passwords#edit', as: :edit_user_password
    patch 'password', to: 'devise/passwords#update', as: :user_password
    put 'password', to: 'devise/passwords#update'
    post 'password', to: 'devise/passwords#create'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shot
  validates :reply, presence: true
end

app/models/shot.rb
class Shot < ApplicationRecord
  has_many :comments
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :shots
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_shot, only: [:create, :destroy]
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @shot = Shot.find(params[:shot_id])
    @comment = @shot.comments.create(comment_params)
    @comment.user_id = current_user.id if current_user
    @comment.save!
    redirect_to shot_path(@shot)
  end

  def destroy
    @shot = Shot.find(params[:shot_id])
    @comment = @shot.comments.find(params[:id])
    @comment.destroy
    redirect_to shot_path(@shot)
  end

  private

  # def set_shot
  #   @shot = Shot.find(params[:shot_id])
  # end

  def comment_params
    params.require(:comment).permit(:reply, :user_id, :shot_id)
  end
end

# class CommentsController < ApplicationController
#   before_action :set_comment, only: [:show, :edit, :update, :destroy]
#
#   # GET /comments
#   # GET /comments.json
#   def index
#     @comments = Comment.all
#   end
#
#   # GET /comments/1
#   # GET /comments/1.json
#   def show
#   end
#
#   # GET /comments/new
#   def new
#     @comment = Comment.new
#   end
#
#   # GET /comments/1/edit
#   def edit
#   end
#
#   # POST /comments
#   # POST /comments.json
#   def create
#     @comment = Comment.new(comment_params)
#
#     respond_to do |format|
#       if @comment.save
#         format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
#         format.json { render :show, status: :created, location: @comment }
#       else
#         format.html { render :new }
#         format.json { render json: @comment.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # PATCH/PUT /comments/1
#   # PATCH/PUT /comments/1.json
#   def update
#     respond_to do |format|
#       if @comment.update(comment_params)
#         format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
#         format.json { render :show, status: :ok, location: @comment }
#       else
#         format.html { render :edit }
#         format.json { render json: @comment.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # DELETE /comments/1
#   # DELETE /comments/1.json
#   def destroy
#     @comment.destroy
#     respond_to do |format|
#       format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end
#
#   private
#   # Use callbacks to share common setup or constraints between actions.
#   def set_comment
#     @comment = Comment.find(params[:id])
#   end
#
#   # Only allow a list of trusted parameters through.
#   def comment_params
#     params.require(:comment).permit(:reply, :user_id, :shot_id)
#   end
# end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /shots
  # GET /shots.json
  def index
    @shots = Shot.all
  end

  # GET /shots/1
  # GET /shots/1.json
  def show
  end

  # GET /shots/new
  def new
    @shot = current_user.shots.build
  end

  # GET /shots/1/edit
  def edit
  end

  # POST /shots
  # POST /shots.json
  def create
    @shot = current_user.shots.build(shot_params)

    respond_to do |format|
      if @shot.save
        format.html { redirect_to root_path, notice: 'Shot was successfully created.' }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shots/1
  # PATCH/PUT /shots/1.json
  def update
    respond_to do |format|
      if @shot.update(shot_params)
        format.html { redirect_to root_path, notice: 'Shot was successfully updated.' }
        format.json { render :show, status: :ok, location: @shot }
      else
        format.html { render :edit }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1
  # DELETE /shots/1.json
  def destroy
    @shot.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Shot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shot_params
      params.require(:shot).permit(:title, :description, :image, :user_id)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(_resource)
    new_user_session_url
  end
end


app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(_resource)
    root_path
  end
end


app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% @shot.comments.each do |comment| %>
  <div>
    <p style="display: inline"><strong><%= comment.user.name %>: </strong><%= comment.reply %></p>
    <% if user_signed_in? && comment.user_id == current_user.id %>
      <button style="display: inline"><%= link_to 'Delete', [comment.shot, comment], method: :delete, data: { confirm: 'Are you sure?' } %></button>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@shot, @shot.comments.build] do |form| %>

  <% @shot.comments.each do |comment| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.label :reply %>
    <%= form.text_area :reply %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dribble</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if current_user %>
  <button><%= link_to 'Home', root_path %></button>
  <button><%= link_to 'Profile', user_path(current_user.id) %></button>
  <button><%= link_to 'Logout', destroy_user_session_path, method: :delete %></button>
  <hr>
  <hr>
  <hr>
<% end %>
<%= yield %>
</body>
</html>

app/views/shots/_feed.html.erb
<h3>Shots Feed </h3>

<br>

<% @shots.each do |shot| %>
  <% if shot.user_id != current_user.id %>

    <div>
      <div style="display: inline">
        <img style="width: 100px; height: 100px" src="<%= shot.image %>"/>
      </div>
      <div>
        <p>
          <strong>Name: </strong>
          <%= shot.user.name %>
        </p>
        <p>
          <strong>Username: </strong>
          <%= shot.user.username %>
        </p>
        <p>
          <strong>Title: </strong>
          <%= shot.title %>
        </p>
        <p>
          <strong>Description: </strong>
          <%=truncate(shot.description, length: 60) %>
        </p>
        <p>
          <strong>Time: </strong>
          <%=time_ago_in_words(shot.created_at) %>
        </p>
        <p><strong><%= pluralize(shot.comments.count, 'Comment') %></strong></p>
        <button><%= link_to 'Show', shot %></button>
      </div>
    </div>
    <br>
    <hr>
    <br>

  <% end %>
<% end %>

app/views/shots/_form.html.erb
<%= form_for @shot, html: { multipart: true } do |form| %>
  <% if @shot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shot.errors.count, "error") %> prohibited this shot from being saved:</h2>

      <ul>
        <% @shot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shots/_profile.html.erb
<p id="notice"><%= notice %></p>

<div>
  <p style="display: inline"><%= current_user.name %>(@<%= current_user.username %>)</p>
  <button style="display: inline"><%= link_to 'Edit User', edit_user_registration_path %></button>
  <button style="display: inline"><%= link_to 'Back', root_path %></button>
</div>

<br>

<div>
  <h3 style="display: inline">Your Shots</h3>
  <button style="display: inline"><%= link_to 'New Shot', new_shot_path %></button>
</div>

<br>

<% current_user.shots.each do |shot| %>

  <div>
    <img style="width: 100px; height: 100px;" src="<%= shot.image %>"/>
    <p><strong>Title: </strong><%= shot.title %></p>
    <p><strong>Description: </strong><%= truncate(shot.description, length: 60) %></p>
    <p><strong>Time: </strong><%= time_ago_in_words(shot.created_at) %></p>
    <p><strong><%= pluralize(shot.comments.count, 'Comment') %></strong></p>
  </div>
  <button><%= link_to 'Show', shot %></button>
  <button><%= link_to 'Edit', edit_shot_path(shot) %></button>
  <button><%= link_to 'Destroy', shot, method: :delete, data: { confirm: 'Are you sure?' } %></button>
  <br>
  <br>
<% end %>

app/views/shots/edit.html.erb
<h1>Editing Shot</h1>

<%= render 'form', shot: @shot %>

<%= link_to 'Show', @shot %> |
<%= link_to 'Back', shots_path %>

app/views/shots/index.html.erb
<% if current_user.nil? %>
  <button><%= link_to 'Login', new_user_session_path %></button>
  <button><%= link_to 'Register', new_user_registration_path %></button>
<% else %>

  <%= render 'feed' %>

<% end %>

app/views/shots/new.html.erb
<h1>New Shot</h1>

<%= render 'form', shot: @shot %>

<%= link_to 'Back', shots_path %>

app/views/shots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shot.user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @shot.user.username %>
</p>

<p>
  <strong>Title:</strong>
  <%= @shot.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shot.description %>
</p>

<p>
  <strong>Time: </strong>
  posted <%= time_tag(@shot.created_at, :format => '%d %B %Y at %l:%M %p') %>
</p>

<p>
  <strong>Image Url:</strong>
  <%= @shot.image.to_s %>
</p>

<p>
  <strong>Image:</strong> <br>
  <img style="width: 370px; height: 300px" src="<%= @shot.image_url unless @shot.image.blank? %>"/>
</p>

<% if user_signed_in? && (current_user.id == @shot.user_id) %>

  <%= link_to 'Edit', edit_shot_path(@shot) %> |
  <%= link_to 'Back', shots_path %>

<% end %>

<div>
  <p><strong><%= pluralize(@shot.comments.count, 'Comment') %></strong></p>
  <%= render 'comments/comment' %>
  <hr>
  <% if user_signed_in? %>
    <%= render 'comments/form' %>
  <% else %>
    <p>You need to login to comment</p>
    <button><%= link_to 'Login', new_user_session_path %></button>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= render 'shots/profile' %>